name: Use FibBot Custom Action
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-fibbot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run FibBot Action
        uses: bansikah22/fibbot@master
        with:
          enable_fib: true
          max_threshold: 1000
          github_token: ${{ secrets.GITHUB_TOKEN }}


